[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://careconnect-backend-mw1u.onrender.com/api"
  REACT_APP_ENV = "production"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://careconnect-backend-mw1u.onrender.com/api"
  REACT_APP_ENV = "production"
  CI = "false"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://careconnect-backend-mw1u.onrender.com/api"
  REACT_APP_ENV = "staging"
  CI = "false"
